### ISSUE TITLE
Modify js template as a functional Taiko script

### ISSUE THREAD

**Issue by zabil** [getgauge/gauge-repository#20]
```
$ gauge init js
```

Must be a functional Taiko script so that users can easily start tests for web application.

**Comment by zabil** [comment]
The test should run in headful mode and display the browser window by default.
Add option for headless using environments.

As we support multiple environments create a 'headless' environment and pass this option while initializing taiko.

**Comment by nehashri** [comment]
Another point to note. The offline gauge templates for js also need to be changed.

**Comment by shubhamsc** [comment]
we are creating gauge sample spec file `example.spec` and default properties with gauge confing and writing test in every runner against that. Now if we want to change the default offline js template with taiko, it needs to add a different spec file for js with taiko. that's not a good thing to add new spec file so offline js template will work as `js_simple` template.

**Comment by sguptatw** [comment]
But @shubhamsc that means the offline and online templates for the same command will initialize the project differently. This is not the expected behavior. Like @nehashri suggested, the offline template should also be changed.

**Comment by sriv** [comment]
This is how the offline template works:

- gauge creates the below files:
```
 create  manifest.json
 create  specs
 create  specs/example.spec
 create  .gitignore
 create  env
 create  env/default
 create  env/default/default.properties
```

language runners generate the implementation.

So if offline template for js changes to accomodate this change, it will change for all language runners, which would be incorrect, given taiko is only for JS.

**Comment by sguptatw** [comment]
@sriv That seems to be a technical implementation limitation. The functional requirement is that offline/online template initialization initializes in the same manner.

**Comment by sguptatw** [comment]
**Discussion Update**
The offline template will initialize the project in the simple mode.
