### ISSUE TITLE
gauge-init js should install latest version of taiko

### ISSUE THREAD

**Issue by sguptatw** [getgauge/gauge-repository#22]
**Expected behavior**
gauge-init js should install latest version of taiko.

**Current behavior**
It installs `0.2.0` instead of latest

> Note: The package.json of the template has 
```
"dependencies": {
    "taiko": "^0.2.0"
  }
```
The package.lock file is also checked in which is locked to `0.2.0`

**Comment by negiDharmendra** [comment]
The fix should be available in 389d406.
