### ISSUE TITLE
update ruby_selenium template

### ISSUE THREAD

**Issue by sriv** [getgauge/gauge-repository#33]
Couple of issues noted:

- there is a dependency on `chromedriver-helper` gem which is deprecated. it is recommended to use `webdrivers` gem instead.

- the example asserts on incorrect text. Implementation of `Navigate to Gauge homepage "http://getgauge.io"` step needs to be updated. also, use `gauge.org` instead of `getgauge.io`

**Comment by Debashis9012** [comment]
This issues has been verified and found fixed.
